networks:
  app_network_dev:
    driver: bridge

services:
  timewebapi:
    image: ${DOCKER_REGISTRY-}timewebapi
    networks:
      - app_network_dev
    build:
      context: .
      dockerfile: TimeWebApi/Dockerfile
    ports:
      - "8080:8080"
      - "8081:8081"

  app_db_dev:
    image: postgres-en-us-utf8
    build:
      context: .
      dockerfile: postgres-en_US-UTF8-config
    container_name: app_db_dev
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin1 # should be stronger :)
      - POSTGRES_DB=TimeWebApiDb
      - POSTGRES_INITDB_ARGS='--locale=en_US.UTF8'
    networks:
      - app_network_dev
    ports:
      - "5433:5432"
    restart: always
    volumes:
      - app_data_dev:/var/lib/postgresql/data

volumes:
  app_data_dev:
